### ISSUE TITLE
Question: Is it possible to re-prompt 2FA?

### ISSUE THREAD

**Issue by marlocorridor** [Visanduma/nova-two-factor#13]
Is it possible to re-prompt 2FA on specified actions, routes, etc.?

This is what I tried so far.

```php
use PragmaRX\Google2FALaravel\Support\Constants;

session(['google2fa.' . Constants::SESSION_AUTH_PASSED => false]);
```

As you can see, it goes all the way to `PragmaRX\Google2FALaravel` package. 😄

It might be nice if we could add `re-prompt` feature, if still not implemented.

**Comment by lahirulhr** [comment]
Hi. we haven't plan for it. but it is possible to do using new Inertia Vue page & few middleware tweaks.

**Comment by marlocorridor** [comment]
@lahirulhr, I'm willing to try to contribute. Please guide me how. :)

**Comment by lahirulhr** [comment]
> @lahirulhr, I'm willing to try to contribute. Please guide me how. :)

I have good a news. currently i'm working on this feature 👍

**Comment by marlocorridor** [comment]
🚀 It is truly a good news!
