### ISSUE TITLE
When i deactivate 2FA, it still ask me

### ISSUE THREAD

**Issue by javierlopezyurda** [Visanduma/nova-two-factor#14]
I deactivate 2FA but in next login its still enabled. I am using Postgresql database and this Middleware fails but with this change no.

TwoFa.php

// turn off security if 2fa is off
 if(auth($this->novaGuard)->user()->twoFa && auth($this->novaGuard)->user()->twoFa->google2fa_enable === 0){
            return $next($request);
        }

Solve with this change:
// turn off security if 2fa is off
 if(auth($this->novaGuard)->user()->twoFa && **!auth($this->novaGuard)->user()->twoFa->google2fa_enable**){
            return $next($request);
        }

**Comment by lahirulhr** [comment]
Hi. 

The middleware issue is already noted & fixed. it will be available with next release (v2.2.0). however , thank you for reporting the issue.

**Comment by jjlopeztrevenque** [comment]
Thanks, when will be available the next release?

**Comment by lahirulhr** [comment]
We have released v2.2 today. Just update your composer.👍
