### ISSUE TITLE
Error shown when opening the Two Factor Page from the sidebar

### ISSUE THREAD

**Issue by andrebreia** [Visanduma/nova-two-factor#17]
When opening the page for a user that doesn't have 2FA record in the database, it throws the error below. After refreshing the page the record is created and the error doesn't show again for that user.
<img width="433" alt="image" src="https://user-images.githubusercontent.com/17434432/197167231-025e99a4-a253-4a6f-8105-9dce6ef2d0de.png">

Looking at the request, the error seems to come from the `getStatus()` function in the `TwoFactorController`.

**Comment by lahirulhr** [comment]
Fixed in v2.2.1  Thank you for reporting the issue.
