### ISSUE TITLE
How to go back to setup device?

### ISSUE THREAD

**Issue by rafaelsmith** [Visanduma/nova-two-factor#21]
After disable it on my user I can only enable it back.
But what if I want to set it up on anther device?

**Comment by NoahNxT** [comment]
Same issue here. Once disabled, it won't remove the 2FA, it just disables it. If the user lost his 2FA codes, there is no possibility to recover except going in the database and remove the record manually

**Comment by lahirulhr** [comment]
@rafaelsmith @NoahNxT. Yes.  currently it is only disable the 2FA record. i hope it may helpful if we have "Clear" button to remove 2FA record. let us  implement this feature asap.

 Thank you for the suggestion

**Comment by lahirulhr** [comment]
Settings  clear feature Added  (v2.2.2)
