### ISSUE TITLE
Publish migration error

### ISSUE THREAD

**Issue by NickvanBakelL** [Visanduma/nova-two-factor#29]
If i run the publish command to publish the migrations:
`php artisan vendor:publish --provider="Visanduma\NovaTwoFactor\ToolServiceProvider"`

It will publish the migration in my migration folder but the migrations have dates 
For example: 2018_12_31_095425_create_nova_twofa_table.php

My first migration is in 2019 so my user table is not created before the migrations of this package.

The error of the php artisan migrate command is:
`SQLSTATE[HY000]: General error: 1215 Cannot add foreign key constraint (Connection: mysql, SQL: alter table `nova_twofa` add constraint `nova_twofa_user_id_foreign` foreign key (`user_id`) references `users` (`id`))`

**Comment by FabrizioKruisland** [comment]
I am experiencing the same problem. Would be awesome if the date of migration can be generated based on current date. Maybe this Medium article is relevant: https://darkghosthunter.medium.com/laravel-packages-load-or-publish-migrations-119db770c870

**Comment by lahirulhr** [comment]
Hi. @NickvanBakelL @FabrizioKruisland 

as you already know , you can resolve this by renaming the published migration files for now. certainly we will add the better solution into package core.

Thank you for reporting the issue.

**Comment by NickvanBakelL** [comment]
Hi @lahirulhr
Renaming the migration does not work because it still runs the migration in the background. Even if i remove the migration. 
If i want to run some tests on my code i need to refresh the database every time. So it keeps crashing.

Hope you can do something 👍🏼

**Comment by lahirulhr** [comment]
Hmm. Package may run migrations it self. Let's do something 👍

**Comment by lahirulhr** [comment]
Automatic migration has been removed from v2.2.5. migration timestamps may customize able now.
