### ISSUE TITLE
regularly forced to reauthorize

### ISSUE THREAD

**Issue by mrvnklm** [Visanduma/nova-two-factor#32]
I am forced to reauthorize quite often during the day, even though I have no `reauthorize_urls` defined and the `reauthorize_timeout` is set to `10080` which is a week

**Comment by lahirulhr** [comment]
Hi, i tried to recreate the issue. but everything works as expected. 
are you sure  "reauthorize_urls" array is empty ?

**Comment by tominal** [comment]
This is still relevant. `reauthorize_urls` is empty but I still have to reauthorize way too much. Mine is set to 48 hours in minutes but still re-authorizes within the hour.

**Comment by andersespedalen** [comment]
Still relevant. I experience the same. Please reopen
