### ISSUE TITLE
Prompt only showing when default guard is web

### ISSUE THREAD

**Issue by tiagoraposeiraff** [Visanduma/nova-two-factor#33]
In my current Laravel app, the default auth is set to `api`, and nova is set to `web`.
I can only get the 2fa prompt to show after login if I change the default auth to `web`, which would break the existing app.

Is there's something else I should be doing to get it to work or is it a bug? thanks!

**Comment by lahirulhr** [comment]
Hi. it is looks like a bug.  fix will be available soon withing next minor version release. hope we can publish it today. 

thank you for reporting the issue 👍

**Comment by tiagoraposeiraff** [comment]
@lahirulhr thank you for the immediate response! let me know once that's published and I will be happy to test it

**Comment by lahirulhr** [comment]
v2.2.6 is available now with improvements

**Comment by tiagoraposeiraff** [comment]
@lahirulhr TY! 
So, now I don't need to change the default guard and seems to work fine, however, when I try to "clear settings" it always give me an `incorrect password` message.
This is because the `current_password` validation also uses the default guard, not the Nova one. Updating the validation to something like `current_password:' . config('nova.guard')` should do the trick
