### ISSUE TITLE
redirect to prior url after reauthorizing

### ISSUE THREAD

**Issue by mrvnklm** [Visanduma/nova-two-factor#37]
Would it be possible to be forwarded to the prior url I clicked instead of the home page?

**Comment by lahirulhr** [comment]
by default , all success authorization attempts are automatically redirected to the relevant indented URL (using session)

**Comment by mrvnklm** [comment]
when I click a link like for instance `/resources/orders/1234` I will be asked to reauthorize before being forwareded to `/dashboards/main`

**Comment by lahirulhr** [comment]
I'm still unable to reproduce the bug. It works as expected.

**Comment by mrvnklm** [comment]
Weird, I will look into it, maybe some issue with a different middleware. Thank you for testing though
