### ISSUE TITLE
Ask code to page that are not protected by authentication 

### ISSUE THREAD

**Issue by henryavila** [Visanduma/nova-two-factor#38]
If I log in in the app and it ask for the 2FA token, if another page that are public (don't require authentication) is opened, the page can't be access without entering 2FA token

**Comment by lahirulhr** [comment]
Hi. it's looks like, the  ```\Visanduma\NovaTwoFactor\Http\Middleware\TwoFa::class``` middleware  was registered inside the main applications kernal.php. it must be register on nova config file.
