### ISSUE TITLE
OTP Nova View

### ISSUE THREAD

**Issue by CodeWithDennis** [Visanduma/nova-two-factor#4]
It seems like it will never ask for my OTP when logging in. Am i missing something?

`
if (auth()->guest() || $authenticator->isAuthenticated()) {
     return $next($request);
}
`

Looks like something here maybe?

**Comment by lahirulhr** [comment]
Hi

Did you add middleware to nova config

``` \Visanduma\NovaTwoFactor\Http\Middleware\TwoFa::class```

**Comment by CodeWithDennis** [comment]
Yes, i did.

Edit: I even tried again from scratch and when i logout and login im not getting any prompt/view.

**Comment by lahirulhr** [comment]
I'm unable to reproduce the issue. please make sure Nova Two factor is

1)  Enabled by config (.env)
2)  Enabled by Nova dashboard settings

**Comment by CodeWithDennis** [comment]
<img width="1449" alt="Schermafbeelding 2022-08-30 om 08 34 23" src="https://user-images.githubusercontent.com/23448484/187366590-0451f2dd-6d7c-4d43-9db9-202364821a9d.png">

![Schermafbeelding 2022-08-30 om 08 34 30](https://user-images.githubusercontent.com/23448484/187366597-ed72e18e-c851-4bfc-acce-27e34869b40d.png)

![Schermafbeelding 2022-08-30 om 08 34 51](https://user-images.githubusercontent.com/23448484/187366600-c2b87d4d-9626-4497-aff2-772784cf9902.png)

Edit:

When i `dumpdie` in the middleware it does pass through it so thats a good thing.

Did all those, see screenshots.

**Comment by lahirulhr** [comment]
All things looks good.

Please make sure User model has  used ```Visanduma\NovaTwoFactor\ProtectWith2FA``` trait

Also try to remove old 2fa record from database table

**Comment by CodeWithDennis** [comment]
<img width="982" alt="Schermafbeelding 2022-08-31 om 08 46 20" src="https://user-images.githubusercontent.com/23448484/187611659-5893777f-eefe-440b-acf2-766b6e71c818.png">

I also have that, im really confused whats going on. Can it be conflicting?

**Comment by lahirulhr** [comment]
it may not conflicting with others but i guess this issue is related to middleware.  let's try to find out what's going on. 

try to diedump following things before first ```if``` condition in middleware

```auth()->user()->twoFa```

**Comment by CodeWithDennis** [comment]
Hi,

I made a small clip for you to check i hope it helps:

[removed link]

**Comment by lahirulhr** [comment]
Thank you for clip. we tried with two fresh Nova 4 projects & it still work without any issue. 

unfortunately i'm unable to reproduce the issue as yours. if you have any special environment setup please let me know. for further support you can contact us directly via info@visanduma.com

**Comment by CodeWithDennis** [comment]
Alright, thanks for trying ill take a deeper look on my end what might be going on.

**Comment by marlocorridor** [comment]
> Alright, thanks for trying ill take a deeper look on my end what might be going on.

Hi, I'm experiencing. No prompt for 2FA.

I will try clearing the caches.

**Comment by marlocorridor** [comment]
I run the following commands:
* `artisan config:cache`
* `artisan optimize:clear`

now fixed

**Comment by CodeWithDennis** [comment]
> I run the following commands:
> 
> * `artisan config:cache`
> * `artisan optimize:clear`
> 
> now fixed

I tried your fix but still not getting a prompt.

**Comment by marlocorridor** [comment]
You could verify if any middleware codes are executed. 
I tried using `dd` or try to `Log` messages.

Before I clear the caches, they are not executed.
