### ISSUE TITLE
How to prevent 2FA disable once set?

### ISSUE THREAD

**Issue by tomcodes** [Visanduma/nova-two-factor#44]
Hi! Thanks for the great package, it works flawlessly.

I was wondering if, once enabled, there was a way to disable access to the `/nova/nova-two-factor` route?

I do not want my users to be able to remove 2FA once setup ;)

Thank you!

**Comment by lahirulhr** [comment]
There are no any inbuilt method. but you can use Laravel middleware to accomplish this. just check for the url  ```/nova/nova-two-factor``` & redirect to somewhere else
