### ISSUE TITLE
btn and btn-primary class dose not work in components

### ISSUE THREAD

**Issue by masoudtajer** [Visanduma/nova-two-factor#48]
btn and btn-primary is no longer available in Nova 4. You can either create new CSS for it or use DefaultButton component.

https://github.com/laravel/nova-issues/discussions/5479

**Comment by toddb02** [comment]
FYI - This is due to the removal of the `LoadingButton` component in a recent update of Nova.

https://github.com/laravel/nova-issues/discussions/6025

**Comment by lahirulhr** [comment]
Thank you for reporting the issue  

@masoudtajer @toddb02 

issue was fixed in [v2.2.11](https://github.com/Visanduma/nova-two-factor/releases/tag/2.2.11)
