### ISSUE TITLE
Blank screen when accesing Twi FA from menu

### ISSUE THREAD

**Issue by SebastianBotez** [Visanduma/nova-two-factor#56]
Hello guys.
I have a problem using Nova 4 (4.33.3 preciesely).
When I press the Two FA button from nova admin I'm getting a blank popup page.

<img width="934" alt="Screenshot 2024-04-20 at 10 54 01" src="https://github.com/Visanduma/nova-two-factor/assets/10911720/ca0e065d-cb87-435a-a622-245db4824839">

**Comment by lahirulhr** [comment]
Hi @SebastianBotez 

You mean Two FA menu button ?

![image](https://github.com/Visanduma/nova-two-factor/assets/13136764/54609b3d-1385-42a4-aa1b-9d5d01a9d8f8)

However, I just updated my Nova version to (4.33.3) and it still works

**Comment by lahirulhr** [comment]
Closed since there was no response
