### ISSUE TITLE
translations are not loaded on middleware forms

### ISSUE THREAD

**Issue by scramatte** [Visanduma/nova-two-factor#59]
Hi,

Translations are not loaded on middleware forms 
recover.blade.php ,  sign-in.blade.php  ...

Regards

**Comment by lahirulhr** [comment]
Hi,

We couldn't find any issues with the translation. Did you use the correct language files located at `lang\vendor\nova-two-factor\` ?

**Comment by scramatte** [comment]
Hi,

Yes, I’m using correct files as  translation is working for .vue template but not for blades files.

Regards

De: LaHiRu ***@***.***>
Responder a: Visanduma/nova-two-factor ***@***.***>
Fecha: martes, 28 de mayo de 2024, 7:15
Para: Visanduma/nova-two-factor ***@***.***>
CC: * * ***@***.***>, Author ***@***.***>
Asunto: Re: [Visanduma/nova-two-factor] translations are not loaded on middleware forms (Issue #59)


Hi,

We couldn't find any issues with the translation. Did you use the correct language files located at lang\vendor\nova-two-factor\ ?

**Comment by lahirulhr** [comment]
I'm sorry. i could not reproduce the issue at my end. Blade translations are working for me. What is your Laravel version?
