### ISSUE TITLE
The QRCode in offline mode is not displayed

### ISSUE THREAD

**Issue by illambo** [Visanduma/nova-two-factor#61]
Package version: v2.2.13

The QRCode in offline mode is not displayed.

The problem is related `$isSvg` variable.

https://github.com/Visanduma/nova-two-factor/blob/0043428fe6d233bf1407a6ef2c8d0da369bfb7ad/src/Http/Controller/TwoFactorController.php#L80

I propose a [PR](https://github.com/Visanduma/nova-two-factor/pull/60) to fix the problem.
Thank you.

**Comment by lahirulhr** [comment]
Hi, actually, `$isSvg` should be `true`. because offline QR is generated as SVG. also i tried switching the QR offline & online and it works well. it looks like browser cache issue. please could you try hard reloading the page?

**Comment by illambo** [comment]
Hi, with `$isSvg = true` this is the generated output:

<img width="1577" alt="Screenshot 2024-05-27 alle 19 34 15" src="https://github.com/Visanduma/nova-two-factor/assets/1899805/6fbae538-49bf-445f-ba80-2fd3e88f07e9">

I don't think the problem is related to the cache.
What do you think? Thanks

**Comment by lahirulhr** [comment]
![image](https://github.com/Visanduma/nova-two-factor/assets/13136764/363f85da-40bf-4643-96d3-2925d7b2c4c1)

I don't know why you got the QR code as a PNG image.
This package uses `bacon/bacon-qr-code` for QR generation. 
Did you make any global configurations for it somewhere else (service providers, etc.)??

**Comment by illambo** [comment]
I think I found the problem, you need to make sure you use the $qrCodeService Bacon and $imageBackEnd SvgImageBackEnd otherwise it depends on the presence or absence of the imagick extension.

See:
https://github.com/antonioribeiro/google2fa-qrcode/blob/ddb1606a1e843530144862e94877b45ea6350485/src/QRCode/Bacon.php#L72
and 
https://github.com/antonioribeiro/google2fa-qrcode/blob/ddb1606a1e843530144862e94877b45ea6350485/src/QRCode/Bacon.php#L39

I've updated the [PR](https://github.com/Visanduma/nova-two-factor/pull/60), let me know what you think.
Thank you.

**Comment by illambo** [comment]
Maybe at this point the pr #53 give more flexibility about this.

**Comment by lahirulhr** [comment]
Your PR #60 looks good and simple. i'm going to merge it.

Thank you for support
