### ISSUE TITLE
QR code Image 404 error

### ISSUE THREAD

**Issue by vladles** [Visanduma/nova-two-factor#62]
The generated QR code link has 404 error (all service chart.googleapsis.com has 404) 
https://chart.googleapis.com/chart?chs=500x500&chld=M|0&cht=qr&chl=otpauth%3A%2F%2Ftotp%2F......

Seems like https://chart.googleapis.com is deprecated 
https://developers.google.com/chart/infographics/docs/qr_codes

**Comment by lahirulhr** [comment]
This issue has already been resolved. please update to latest version [v2.2.13](https://github.com/Visanduma/nova-two-factor/releases/tag/2.2.13)
