### ISSUE TITLE
Question: except_routes / mandatory_routes

### ISSUE THREAD

**Issue by interpegasus** [Visanduma/nova-two-factor#63]
First of all, thanks for sharing this useful library. Great job!

I have a question. At the moment, users can opt to enable MFA. Is it possible to make MFA mandatory to access certain routes, such as '/resources/users' or even all routes in Laravel Nova until 2FA is enabled?

Thanks.

**Comment by lahirulhr** [comment]
Hi

Currently, there is no built-in feature to achieve this behavior. but you can easily create your own `middleware` to accomplish this.
