### ISSUE TITLE
[NOVA 4] CSS Button style

### ISSUE THREAD

**Issue by jodhaakbar** [Visanduma/nova-two-factor#8]
hi,

when create a resources, create button show like this

![before2fa](https://user-images.githubusercontent.com/12839471/188541058-85252d41-f872-406d-b81d-d1034e5b2987.jpg)

i am trying to fix it, i found that your styles efecting the whole themes.

![after2fa](https://user-images.githubusercontent.com/12839471/188541250-67036a15-db64-4fe9-ba90-400519356ad7.jpg)

`background-color:transparent;`

please kindly to fix this issue.

thank you

**Comment by jodhaakbar** [comment]
i think, you need to compile first your tools asset, it should be fix the issue

![fixing2fa](https://user-images.githubusercontent.com/12839471/188544096-9102018b-52f8-4952-b716-19131897a6fc.jpg)

**Comment by lahirulhr** [comment]
Thank you reporting the issue. we made quick fix with  v2.0.2
